DECLARE @vezes
SET @vezes = 1

WHILE @vezes <= 1000
BEGIN
    INSERT INTO registro (registro, dtHora, fkHasComponente) VALUES
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 1)
    SET @vezes = @vezes + 1
END

WHILE @vezes <= 1000
BEGIN
    INSERT INTO registro (registro, dtHora, fkHasComponente) VALUES
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5),
    (FLOOR(RAND() * 101), GETDATE() - CAST(FLOOR(RAND() * 1075) AS INT), FLOOR(RAND() * 2) + 5)
    SET @vezes = @vezes + 1
END
